---
- name: Install & configure Tomcat
  hosts: centos_server
  become: yes
  gather_facts: yes
  vars:
    java_version: java-1.8.0-openjdk  # You should install Java separately
    req_tomcat_ver: 10.1.35
    tomcat_port: 8090
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-{{ req_tomcat_ver.split('.')[0] }}/v{{ req_tomcat_ver }}/bin/apache-tomcat-{{ req_tomcat_ver }}.tar.gz"
    tomcat_home: /usr/local/tomcat_10  # Define Tomcat's home directory
    tomcat_user: tomcat  # User to run Tomcat as
    tomcat_group: tomcat # Group to run Tomcat as

  tasks: 
    - name: Create Tomcat group if it doesn't exist
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user and group
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        create_home: no
        system: yes

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ req_tomcat_ver }}.tar.gz" # Download to /tmp
        validate_certs: no # Consider setting to yes if you can verify the certificate
      tags:
        - download

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ req_tomcat_ver }}.tar.gz"
        dest: "/tmp"
        remote_src: yes
      tags:
        - extract

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_home }}"
        state: directory
        mode: 0755
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      tags:
        - create_dir

    - name: Move Tomcat installation
      command: rsync -avzP  /tmp/apache-tomcat-{{req_tomcat_ver}}/ "{{ tomcat_home }}"
      tags:
          - move
    - name: Change ownership of Tomcat directory
      file: 
        path: "{{ tomcat_home }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Replace default port of Tomcat
      template:
          src: template/server.xml.j2
          dest: "{{ tomcat_home }}/conf/server.xml"
      tags:
          - config
    - name: Create Tomcat service file
      template:
        src: template/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      tags: 
         - service
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
      tags:
      - reload    
      
    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started
      tags: 
      - started



    