---
- name: Installed and configure Kafka
  hosts: centos_server
  gather_facts: false
  become: yes
  vars: 
    req_kafka_ver: 2.13-3.8.1
    kafka_url: https://dlcdn.apache.org/kafka/3.8.1/kafka_{{ req_kafka_ver }}.tgz
    java_version: java-11-openjdk
    kafka_user: kafka
    kafka_group: kafka
    kafka_home: /home/kafka
  tasks: 
    - name: Ensure Java is installed (example - adapt as needed)
      package:
        name: "{{ java_version }}"
        state: present
    
    - name: Download  kafka for centos 
      get_url: 
         url: https://dlcdn.apache.org/kafka/3.8.1/kafka_{{ req_kafka_ver }}.tgz
         dest: /tmp
    - name: Extract the file 
      unarchive:
        src: /tmp/kafka_{{ req_kafka_ver }}.tgz
        dest: /tmp/
        remote_src: yes
      tags: 
       - unarchive
    - name: Move the file 
      command: rsync -avzP /tmp/kafka_{{ req_kafka_ver }}/*  "{{ kafka_home }}/kafka"
      tags: 
      - move
    - name: Create zookeeper service
      template: 
        src: template/zookeeper.service.j2
        dest: /etc/systemd/system/zookeeper.service
    - name: Create kafka service
      template:
         src: template/kafka.service.j2
         dest: /etc/systemd/system/kafka.service
      tags: 
      - service