---
- name: Install & configure Tomcat
  hosts: centos_server
  become: yes
  gather_facts: yes
  vars: 
     java_version: java-1.8.0-openjdk
     req_tomcat_ver: 11.0.4
     tomcat_port: 8090
     tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-{{ req_tomcat_ver.split('.')[0] }}/v{{ req_tomcat_ver }}/bin/apache-tomcat-{{ req_tomcat_ver }}.tar.gz"
  tasks: 
    - name: Download url 
      get_url:
         url: "{{ tomcat_url }}"
         dest: "/usr/local/apache-tomcat-{{ req_tomcat_ver }}.tar.gz"
      tags:
        - url
    - name: Extract tar file
      unarchive:
         src: /usr/local/apache-tomcat-{{ req_tomcat_ver }}.tar.gz
         dest: /tmp
         remote_src: yes
      tags: 
        - unarchive
    - name: change name and move to /usr/local
      command: mv /tmp/apache-tomcat-{{req_tomcat_ver}} /usr/local/tomcat_latest
      tags:
       - rename
    - name: Run tomcat application 
      shell: nohup /usr/local/tomcat_latest/bin/startup.sh &
      tags: 
      - start
    - name: replace default port of Tomcat 
      template:
         src: template/server.xml.j2
         dest: /usr/local/tomcat_latest/conf/server.xml
      tags:
         - port