---
- hosts: all
  become: true
  vars: 
     username:     # add username
     comment: 
     groupname:    # add groupname
     userid: 1002  # add userid 
     groupid: 1112  # add groupid 
  tasks: 
  - name: create a new user
    user:
        name: "{{ username }}" 
        comment: "{{ comment }}"
        uid: "{{ userid }}"   # set the uid 
    tags: user
  - name: create a new group on remote hosts
    group:
        name: "{{ groupname }}" #add a new group
        gid: "{{ groupid }}" #( add gid )
    tags: group
   
  - name: Make sure user must be added in group
    shell: usermod -aG "{{ groupname }}" "{{ username }}"
    tags: usermod



