- name: Copy Ubuntu packages to the target server
  ansible.builtin.copy:
    src: /home/sarvind/ansible/Ubuntu_packages
    dest: /tmp
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- name: Make ubuntu.sh script executable for Ubuntu
  ansible.builtin.file:
    path: /tmp/Ubuntu_packages/ubuntu.sh
    mode: '0755'
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- name: Run ubuntu.sh script
  ansible.builtin.shell: |
    ./ubuntu.sh
  args:
    chdir: /tmp/Ubuntu_packages
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- name: Copy additional script to target server for Ubuntu
  ansible.builtin.copy:
    src: Ubuntu-config.sh
    dest: /tmp/Ubuntu_packages/Ubuntu-config.sh
    mode: '0755'
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- name: Run Ubuntu-config.sh script
  ansible.builtin.shell: |
    ./Ubuntu-config.sh
  args:
    chdir: /tmp/Ubuntu_packages
  when: ansible_distribution == "Ubuntu"
  tags:
    - ubuntu

- name: Copy CentOS-config.sh to the target server
  ansible.builtin.copy:
    src: CentOS-config.sh
    dest: /tmp
    mode: '0755'
  when: ansible_distribution == "CentOS"
  tags:
    - centos

- name: Run CentOS-config.sh script
  ansible.builtin.shell: |
    ./CentOS-config.sh
  args:
    chdir: /tmp
  when: ansible_distribution == "CentOS"
  tags:
    - centos

