apache_package_name: apache2
apache_service: apache2
php_package_name: libapache2-mod-php

ssh_service: ssh

username: bharats
uid: 2103
passwd: bharat123

gid: 1108
groupname: interns

usbguard_rules:
  - "allow with-interface one-of {03:01:02}"
  - "allow with-interface one-of {03:01:01}"

usbguard_service: usbguard

sudo_rules:
      - "{{ username }} ALL=NOPASSWD: /usr/sbin/openvpn *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/systemctl restart *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/systemctl start onedrive@alex.service"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/systemctl stop onedrive@alex.service"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/mount *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/umount *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/tail *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/less *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/killall *"
      - "{{ username }} ALL=NOPASSWD: /usr/bin/sh *"

